In [4]:
#Question1
'''Write a function to compute 5/0 and use try/except to catch the exceptions. '''
def func_exceptions():
    while True:
        try:
            x=int(input("Enter Numerator(x):"))
            y=int(input("Enter Denominator(y):"))
            a=x/y
        except ZeroDivisionError:
            print("Division by zero. Please check the denominator")
            continue
        except ValueError:
            print("Entered input is a non-integer. Please enter integer value")
            continue
        else:
            print("Division Successful!!x divided by y is equal to {}".format(a))
            break
            
func_exceptions()

Enter Numerator(x):1
Enter Denominator(y):0
Division by zero. Please check the denominator
Enter Numerator(x):1
Enter Denominator(y):e
Entered input is a non-integer. Please enter integer value
Enter Numerator(x):0.5
Entered input is a non-integer. Please enter integer value
Enter Numerator(x):4
Enter Denominator(y):2
Division Successful!!x divided by y is equal to 2.0


In [67]:
#Question 2
'''Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"]
and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].Hint: Subject,Verb and Object should be declared in the program as shown below. 
subjects=["Americans","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"] '''
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for i in subjects:
    for j in verbs:
        for k in objects:
            m=i+" "+j+" "+k
            print(m)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [63]:
#Question 3
'''Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. 
Specifically, when increasing is False, the i-th output column is the input vector raised element-wise
to the power of N - i - 1.  
HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.  
 '''
import numpy as np
x=input("Enter numbers seperated by comma:")
y=list(x.split(","))
l=[]
for i in y:
    l.append(int(i))
arr=np.asarray(l)
p=[]
for j in l:
    n=[]
    for power in range(0,len(l)):
        n.append(j**power)
    n.sort(reverse=True)
    p.append(n)
    
p=np.array(p)

print("Input vector is:{}".format(arr))
print("Alexandre Theophile Vandermonde matrix of the input vector is\n {}".format(p))


Enter numbers seperated by comma:1,2,3,4
Input vector is:[1 2 3 4]
Alexandre Theophile Vandermonde matrix of the input vector is
 [[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
